package naive

import (
	"errors"
	"fmt"
	"strings"
	"text/template"
)

// Options drives the Caddyfile render. Only fields here are
// interpolated into the template; everything else is fixed so an
// operator can't accidentally undo a stealth setting.
type Options struct {
	// Domain is the FQDN clients use. Picked up by tls automation
	// and exposed in the Host directive.
	Domain string

	// ListenPort is where forward_proxy listens. Defaults to 443.
	ListenPort int

	// Email is the ACME contact (optional). When empty, ACME is
	// still issued anonymously — Caddy supports that.
	Email string

	// Username/Password drive the basic_auth challenge that gates
	// the forward_proxy. Empty values are rejected.
	Username string
	Password string

	// ProbeResistance is the secret hostname that disables the
	// proxy's "I am a forward proxy" reply when actively probed.
	// REQUIRED — empty value means an unauthenticated probe can
	// distinguish us from a vanilla webserver.
	ProbeResistance string

	// SiteRoot is the directory served as a static fallback when
	// requests don't carry valid forward-proxy auth. Defaults to
	// [DefaultSiteRoot].
	SiteRoot string

	// AdminSocket overrides Caddy's admin endpoint. Same semantics
	// as the [internal/tls] package: empty → local unix socket,
	// "off" → admin disabled, anything else → emitted verbatim.
	AdminSocket string
}

// Defaults applied by [Render] when a field is left zero.
const (
	DefaultListenPort  = 443
	DefaultSiteRoot    = "/var/lib/xray-aio/naive-selfsteal"
	DefaultAdminSocket = "unix//run/xray-aio/caddy-naive-admin.sock"
)

// caddyfileBadChars is the strict character set rejected in every
// interpolated field — same surface as internal/tls.
const caddyfileBadChars = " \t\r\n{};'\""

// Render returns the Caddyfile for o.
func Render(o Options) (string, error) {
	if o.ListenPort == 0 {
		o.ListenPort = DefaultListenPort
	}
	if o.SiteRoot == "" {
		o.SiteRoot = DefaultSiteRoot
	}
	if o.AdminSocket == "" {
		o.AdminSocket = DefaultAdminSocket
	}
	if err := o.validate(); err != nil {
		return "", err
	}

	tpl, err := template.New("naive").Parse(caddyfileTemplate)
	if err != nil {
		return "", fmt.Errorf("parse template: %w", err)
	}
	var sb strings.Builder
	if err := tpl.Execute(&sb, o); err != nil {
		return "", fmt.Errorf("execute template: %w", err)
	}
	return sb.String(), nil
}

func (o Options) validate() error {
	if err := rejectInjection("Domain", o.Domain); err != nil {
		return err
	}
	if o.Domain == "" {
		return errors.New("Domain is required")
	}
	if o.ListenPort <= 0 || o.ListenPort > 65535 {
		return fmt.Errorf("ListenPort %d out of range", o.ListenPort)
	}
	if o.Username == "" || o.Password == "" {
		return errors.New("Username and Password are required")
	}
	if err := rejectInjection("Username", o.Username); err != nil {
		return err
	}
	if err := rejectInjection("Password", o.Password); err != nil {
		return err
	}
	// basic_auth in Caddyfile is whitespace-separated user pass —
	// even though we already reject whitespace via
	// rejectInjection, we also reject ':' so a hostile password
	// can't be confused with the URL-syntax separator some
	// clients use to encode credentials.
	if strings.ContainsAny(o.Username+o.Password, ":") {
		return errors.New("Username/Password must not contain ':'")
	}
	if o.Email != "" {
		if err := rejectInjection("Email", o.Email); err != nil {
			return err
		}
	}
	if o.ProbeResistance == "" {
		return errors.New("ProbeResistance is required (empty disables the active-probe defense)")
	}
	if err := rejectInjection("ProbeResistance", o.ProbeResistance); err != nil {
		return err
	}
	if !strings.HasPrefix(o.SiteRoot, "/") {
		return fmt.Errorf("SiteRoot must be absolute, got %q", o.SiteRoot)
	}
	if err := rejectInjection("SiteRoot", o.SiteRoot); err != nil {
		return err
	}
	if o.AdminSocket != "off" {
		if err := rejectInjection("AdminSocket", o.AdminSocket); err != nil {
			return err
		}
	}
	return nil
}

func rejectInjection(field, v string) error {
	if strings.ContainsAny(v, caddyfileBadChars) {
		return fmt.Errorf("%s contains invalid characters: %q", field, v)
	}
	return nil
}

// caddyfileTemplate matches the canonical NaïveProxy server config
// pattern: TLS-ALPN-01 ACME on the public port, forward_proxy with
// hide_ip + hide_via + probe_resistance, and a static site root that
// answers for anyone who doesn't carry valid auth (selfsteal).
//
// The domain is interpolated into the site address so Caddy auto-
// issues a Let's Encrypt cert for it (this is Caddy's defining
// feature; Site addresses are the contract Caddy uses to drive the
// ACME handshake). When Email is empty an explicit `tls internal`
// directive forces a self-signed cert — useful for staging without an
// LE account.
const caddyfileTemplate = `# Generated by xray-aio. Do not edit by hand — changes are overwritten.
{
	admin {{ .AdminSocket }}
{{- if .Email }}
	email {{ .Email }}
{{- end }}
}

{{ .Domain }}:{{ .ListenPort }} {
{{- if not .Email }}
	tls internal
{{- end }}
	forward_proxy {
		basic_auth {{ .Username }} {{ .Password }}
		hide_ip
		hide_via
		probe_resistance {{ .ProbeResistance }}
	}
	root * {{ .SiteRoot }}
	file_server
	header {
		Strict-Transport-Security "max-age=31536000; includeSubDomains"
		X-Content-Type-Options nosniff
		Referrer-Policy no-referrer
	}
}
`
