package tls

import (
	"errors"
	"fmt"
	"strings"
	"text/template"
)

// Options drives Caddyfile rendering. Fields not used in the current
// template are reserved for later phases (transport injection,
// upstream forwarders).
type Options struct {
	// Domain is the FQDN used in the certificate (CN). Must be a
	// public DNS name that resolves to this host.
	Domain string

	// Email is registered with Let's Encrypt for renewal notifications.
	// Optional; when empty, Caddy uses a default account.
	Email string

	// SelfStealRoot is the on-disk directory served as the public
	// website (a fake landing page indistinguishable from a static
	// blog). Defaults to [DefaultSelfStealRoot].
	SelfStealRoot string

	// AdminListen overrides Caddy's admin endpoint. Three forms:
	//   ""           → default unix socket at [DefaultAdminSocket],
	//                  reachable only locally; lets us reload config
	//                  without exposing the admin API on the network.
	//   "off"        → emit `admin off` (no API at all; Reload then
	//                  must restart, not reload).
	//   anything else → emitted verbatim (e.g. "127.0.0.1:2019").
	AdminListen string
}

// DefaultSelfStealRoot is where Manager writes the embedded landing
// page during Install.
const DefaultSelfStealRoot = "/var/lib/xray-aio/selfsteal"

// DefaultAdminSocket is the local-only admin endpoint when AdminListen
// is empty. Living under /run lets us declare a [systemd] RuntimeDirectory
// so the directory is created on Start and cleaned on Stop.
const DefaultAdminSocket = "unix//run/xray-aio/caddy-admin.sock"

// caddyfileTemplate intentionally avoids fancy directives: every line
// has a clear job and is easy to audit. Phase 1.3+ will append
// transport blocks via [Manager.Reconfigure].
const caddyfileTemplate = `# Generated by xray-aio. Do not edit by hand — changes are overwritten.
{
	admin {{ .AdminListen }}
{{- if .Email }}
	email {{ .Email }}
{{- end }}
	auto_https disable_redirects
}

# HTTP → HTTPS redirect; ACME HTTP-01 fallback.
http://{{ .Domain }} {
	redir https://{{ .Domain }}{uri} permanent
}

# Public selfsteal landing page over HTTPS (TLS-ALPN-01 ACME).
{{ .Domain }} {
	encode zstd gzip
	root * {{ .SelfStealRoot }}
	file_server
	header {
		X-Content-Type-Options nosniff
		Referrer-Policy strict-origin-when-cross-origin
		-Server
	}
}
`

// caddyfileBadChars is the set of bytes that would let a
// template-substituted value break out of its directive and inject
// further Caddyfile syntax (whitespace, line breaks, brace, semicolon,
// quotes).
const caddyfileBadChars = " \t\r\n{};'\""

// Render returns the Caddyfile body for the given Options. It
// validates the inputs (non-empty domain, no whitespace, no injection
// chars) before touching the template so failures are returned early.
//
// Defaults applied here: SelfStealRoot → [DefaultSelfStealRoot],
// AdminListen "" → [DefaultAdminSocket].
func Render(o Options) (string, error) {
	if err := o.validate(); err != nil {
		return "", err
	}
	if o.SelfStealRoot == "" {
		o.SelfStealRoot = DefaultSelfStealRoot
	}
	if o.AdminListen == "" {
		o.AdminListen = DefaultAdminSocket
	}
	tmpl, err := template.New("caddyfile").Parse(caddyfileTemplate)
	if err != nil {
		return "", fmt.Errorf("parse template: %w", err)
	}
	var b strings.Builder
	if err := tmpl.Execute(&b, o); err != nil {
		return "", fmt.Errorf("execute template: %w", err)
	}
	return b.String(), nil
}

func (o Options) validate() error {
	if strings.TrimSpace(o.Domain) == "" {
		return errors.New("Domain is required")
	}
	if err := rejectInjection("Domain", o.Domain); err != nil {
		return err
	}
	if o.Email != "" {
		if err := rejectInjection("Email", o.Email); err != nil {
			return err
		}
	}
	if o.SelfStealRoot != "" {
		if !strings.HasPrefix(o.SelfStealRoot, "/") {
			return fmt.Errorf("SelfStealRoot must be absolute: %q", o.SelfStealRoot)
		}
		if err := rejectInjection("SelfStealRoot", o.SelfStealRoot); err != nil {
			return err
		}
	}
	if o.AdminListen != "" && o.AdminListen != "off" {
		if err := rejectInjection("AdminListen", o.AdminListen); err != nil {
			return err
		}
	}
	return nil
}

func rejectInjection(field, v string) error {
	if strings.ContainsAny(v, caddyfileBadChars) {
		return fmt.Errorf("%s contains invalid characters: %q", field, v)
	}
	return nil
}
