package tls

import (
	"errors"
	"fmt"
	"strings"
	"text/template"
)

// Options drives Caddyfile rendering. Fields not used in the current
// template are reserved for later phases (transport injection,
// upstream forwarders).
type Options struct {
	// Domain is the FQDN used in the certificate (CN). Must be a
	// public DNS name that resolves to this host.
	Domain string

	// Email is registered with Let's Encrypt for renewal notifications.
	// Optional; when empty, Caddy uses a default account.
	Email string

	// SelfStealRoot is the on-disk directory served as the public
	// website (a fake landing page indistinguishable from a static
	// blog). Defaults to [DefaultSelfStealRoot].
	SelfStealRoot string

	// AdminListen overrides Caddy's admin endpoint. Empty disables it
	// entirely (recommended on internet-exposed hosts).
	AdminListen string
}

// DefaultSelfStealRoot is where Manager writes the embedded landing
// page during Install.
const DefaultSelfStealRoot = "/var/lib/xray-aio/selfsteal"

// caddyfileTemplate intentionally avoids fancy directives: every line
// has a clear job and is easy to audit. Phase 1.3+ will append
// transport blocks via [Manager.Reconfigure].
const caddyfileTemplate = `# Generated by xray-aio. Do not edit by hand — changes are overwritten.
{
{{- if .AdminListen }}
	admin {{ .AdminListen }}
{{- else }}
	admin off
{{- end }}
{{- if .Email }}
	email {{ .Email }}
{{- end }}
	auto_https disable_redirects
}

# HTTP → HTTPS redirect; ACME HTTP-01 fallback.
http://{{ .Domain }} {
	redir https://{{ .Domain }}{uri} permanent
}

# Public selfsteal landing page over HTTPS (TLS-ALPN-01 ACME).
{{ .Domain }} {
	encode zstd gzip
	root * {{ .SelfStealRoot }}
	file_server
	header {
		X-Content-Type-Options nosniff
		Referrer-Policy strict-origin-when-cross-origin
		-Server
	}
}
`

// Render returns the Caddyfile body for the given Options. It
// validates the inputs (non-empty domain, no whitespace) before
// touching the template so failures are returned early.
func Render(o Options) (string, error) {
	if err := o.validate(); err != nil {
		return "", err
	}
	if o.SelfStealRoot == "" {
		o.SelfStealRoot = DefaultSelfStealRoot
	}
	tmpl, err := template.New("caddyfile").Parse(caddyfileTemplate)
	if err != nil {
		return "", fmt.Errorf("parse template: %w", err)
	}
	var b strings.Builder
	if err := tmpl.Execute(&b, o); err != nil {
		return "", fmt.Errorf("execute template: %w", err)
	}
	return b.String(), nil
}

func (o Options) validate() error {
	if strings.TrimSpace(o.Domain) == "" {
		return errors.New("Domain is required")
	}
	if strings.ContainsAny(o.Domain, " \t\r\n{};") {
		return fmt.Errorf("Domain contains invalid characters: %q", o.Domain)
	}
	if o.Email != "" && strings.ContainsAny(o.Email, " \t\r\n{};") {
		return fmt.Errorf("Email contains invalid characters: %q", o.Email)
	}
	if o.SelfStealRoot != "" && !strings.HasPrefix(o.SelfStealRoot, "/") {
		return fmt.Errorf("SelfStealRoot must be absolute: %q", o.SelfStealRoot)
	}
	if o.AdminListen != "" && strings.ContainsAny(o.AdminListen, " \t\r\n{};") {
		return fmt.Errorf("AdminListen contains invalid characters: %q", o.AdminListen)
	}
	return nil
}
